export const FETCH_INEBRIANT = 'FETCH_INEBRIANT';
export const FETCH_HEALTH = 'FETCH_HEALTH';
export const FETCH_PASTRY = 'FETCH_PASTRY';
export const FETCH_DAIRY = 'FETCH_DAIRY';
export const FETCH_FRESH = 'FETCH_FRESH';
export const FETCH_COSMETIC = 'FETCH_COSMETIC';
export const FETCH_CRAFTS = 'FETCH_CRAFTS';